apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace is handled by the parent, but can remain here for local validation
namespace: kube-system 

helmCharts:
  - name: bitnami
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.18.0
    releaseName: bitnami
    namespace: kube-system
    valuesInline:
      admissionController:
        replicas: 1
      backgroundController:
        replicas: 1
      cleanupController:
        replicas: 1
      reportsController:
        replicas: 1