apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aci-mgmt
resources:
  - base        # Points to the directory containing the Helm chart definition
#  - policies    # Points to the directory containing your policies
