apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace is handled by the parent, but can remain here for local validation
namespace: demo-app 

helmCharts:
  - name: demo-app
    repo: "https://github.com/m-gran/devsecops-demo-app"
    version: 3.7.0
    releaseName: demo-app
    namespace: demo-app
