apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace is handled by the parent, but can remain here for local validation
namespace: dev-team-a
resources:
  - deployment.yaml
  - service.yaml
