apiVersion: v1
kind: Service
metadata:
  name: demo-app-devsecops-lab-app
  labels:
    app.kubernetes.io/name: devsecops-lab-app
    app.kubernetes.io/instance: dev-team-a
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      nodePort: 30000
      name: http
  selector:
    app.kubernetes.io/name: devsecops-lab-app
    app.kubernetes.io/instance: dev-team-a
